name: C Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cmake gen
      run: cmake -S . -B build
    - name: build
      run: cmake --build build/
    - name: run tests
      run: cd build && ctest
